# Site settings
name: Flasushi
description: ""
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  Flasushi
#codepen_username: your_codepen_username_goes_here
#facebook_username: your_facebook_username_goes_here
#vk_username: your_vk_username_goes_here
twitter_username: Flasushi
#google_plus_username: your_google_plus_username_goes_here
#linkedin_username: your_linked_in_username_goes_here
#vine_username:  your_vine_username_goes_here
instagram_username:  flasushi
#flickr_username: your_flickr_username_goes_here
#steam_username: your_steam_username_goes_here
soundcloud_username:  osu-shi
#stack_of_username: your_stack_overflow_account_id_number_goes_here
#reddit_username: your_reddit_username_goes_here
#medium_username:  your_medium_username_goes_here
#tumblr_username: your_tumblr_username_goes_here
#weibo_username: your_weibo_username_goes_here
#lastfm_username: your_lastfm_username_goes_here
#blog_url: "/blog"
email: flash.osushi@gmail.com
#public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
# Twitter　icon
avatar_img_path: "https://pbs.twimg.com/profile_images/1064904467466702853/-P_9PzQX_400x400.jpg"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
